import express from "express";
import cors from "cors";
import { apiRoutes } from "./config/apiRoutes.js";
import { env } from "./config/env.js";
import requesterRoutes from "./modules/requesters/requester.routes.js";
import donorRoutes from "./modules/donors/donor.routes.js";
import bloodRequestRoutes from "./modules/blood-requests/bloodRequest.routes.js";
import bloodRequestBankRoutes from "./modules/blood-requests/bloodRequestBank.routes.js";
import bloodBankRoutes from "./modules/blood-banks/bloodBank.routes.js";
import bloodBankInventoryRoutes from "./modules/blood-bank-inventory/bloodBankInventory.routes.js";
import donorEventRoutes from "./modules/notifications/donorEvent.routes.js";
import { notFoundHandler, errorHandler } from "./shared/http/errorHandlers.js";
const app = express();
app.use(cors({ origin: env.corsOrigin, credentials: true }));
app.use(express.json({ limit: "1mb" }));
app.get(apiRoutes.health, (req, res) => {
  res.json({ success: true, message: "HemoConnect360 Backend Running" });
});
app.use(apiRoutes.requesters.base, requesterRoutes);
app.use(apiRoutes.donors.base, donorRoutes);
app.use(apiRoutes.bloodRequests.bankBase, bloodRequestBankRoutes);
app.use(apiRoutes.bloodRequests.base, bloodRequestRoutes);
app.use(apiRoutes.bloodBanks.base, bloodBankRoutes);
app.use(apiRoutes.bloodBanks.base, bloodBankInventoryRoutes);
app.use(apiRoutes.donorEvents.base, donorEventRoutes);
app.use(notFoundHandler);
app.use(errorHandler);
export default app;
