export const apiRoutes = {
  health: "/",
  requesters: {
    base: "/api/requesters",
    phoneLogin: "/phone-login",
    me: "/me",
    profile: "/me/profile",
    pushToken: "/me/push-token",
    notifications: "/me/notifications",
    notificationRead: "/me/notifications/:id/read",
  },
  donors: {
    base: "/api/donors",
    register: "/register",
  },
  bloodBanks: {
    base: "/api/blood-banks",
    register: "/register",
    me: "/me",
    settings: "/settings",
    inventory: "/inventory",
    inventoryHistory: "/inventory/history",
    collections: "/collections",
    collectionHistory: "/collections/history",
    collectionDonors: "/collections/donors",
    collectionDonorDetails: "/collections/donors/:phone",
  },
  bloodRequests: {
    base: "/api/blood-requests",
    bankBase: "/api/blood-requests/blood-bank",
    create: "/",
    list: "/",
    detail: "/:id",
    cancel: "/:id/cancel",
    matches: "/:id/matches",
    bankList: "/",
    bankNearby: "/nearby",
    bankDetail: "/:id",
    bankAccept: "/:id/accept",
    bankReject: "/:id/reject",
    bankComplete: "/:id/complete",
  },
  donorEvents: {
    base: "/api/donor-events",
    outcome: "/outcome",
  },
};

